# Triggers after the "Downstream artifacts" build has finished, to run the
# cypress tests (with access to repo secrets)

name: matrix-react-sdk Cypress End to End Tests
on:
    workflow_run:
        workflows: ["Build downstream artifacts"]
        types:
            - completed

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.run_id }}
    cancel-in-progress: ${{ github.event.workflow_run.event == 'pull_request' }}

jobs:
    cypress:
        permissions:
            actions: read
            issues: read
            statuses: write
            pull-requests: read
        name: Cypress
        uses: richvdh/matrix-react-sdk/.github/workflows/cypress.yaml@rav_work

