# Triggers after the "Downstream artifacts" build has finished, to run the
# cypress tests (with access to repo secrets)

name: matrix-react-sdk Cypress End to End Tests
on:
    workflow_run:
        workflows: ["Build downstream artifacts"]
        types:
            - completed

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.run_id }}
    cancel-in-progress: ${{ github.event.workflow_run.event == 'pull_request' }}

jobs:
    tests:
        name: "Run Tests"
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        permissions:
            actions: read
            issues: read
            pull-requests: read
        environment: Cypress
        strategy:
            fail-fast: false
            matrix:
                # Run 4 instances in Parallel
                runner: [1, 2, 3, 4]
        steps:
            - uses: browser-actions/setup-chrome@c485fa3bab6be59dce18dbc18ef6ab7cbc8ff5f1
            - run: echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

            - uses: tecolicom/actions-use-apt-tools@ceaf289fdbc6169fd2406a0f0365a584ffba003b # v1
              with:
                  # Our test suite includes some screenshot tests with unusual diacritics, which are
                  # supposed to be covered by STIXGeneral.
                  tools: fonts-stix

            # There's a 'download artifact' action, but it hasn't been updated for the workflow_run action
            # (https://github.com/actions/download-artifact/issues/60) so instead we get this mess:
            - name: 📥 Download artifact
              uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2
              with:
                  run_id: ${{ github.event.workflow_run.id }}
                  name: previewbuild
                  path: webapp

            # The workflow_run.head_sha is the sha of the head commit but the element-web was built using a simulated
            # merge commit - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
            # so use the sha from the tarball for the checkout of the cypress tests
            # to make sure we get a matching set of code and tests.
            - name: Grab sha from webapp
              id: sha
              run: |
                  echo "sha=$(cat webapp/sha)" >> $GITHUB_OUTPUT

            - uses: actions/checkout@v3
              with:
                  repository: 'richvdh/matrix-react-sdk'  # FIXME FIXME
                  ref: ${{ steps.sha.outputs.sha }}
                  persist-credentials: false
                  path: matrix-react-sdk

            - name: Run Cypress tests
              uses: cypress-io/github-action@40a1a26c08d0e549e8516612ecebbd1ab5eeec8f
              with:
                  working-directory: matrix-react-sdk
                  # The built-in Electron runner seems to grind to a halt trying
                  # to run the tests, so use chrome.
                  browser: "${{ env.BROWSER_PATH }}"
                  start: npx serve -p 8080 ../webapp
                  wait-on: "http://localhost:8080"
                  record: true
                  parallel: true
                  command-prefix: "yarn percy exec --parallel --"
                  config: '{"reporter":"cypress-multi-reporters", "reporterOptions": { "configFile": "cypress-ci-reporter-config.json" } }'
                  ci-build-id: ${{ needs.prepare.outputs.uuid }}
              env:
                  # pass the Dashboard record key as an environment variable
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

                  # Use existing chromium rather than downloading another
                  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

                  # pass GitHub token to allow accurately detecting a build vs a re-run build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                  # make Node's os.tmpdir() return something where we actually have permissions
                  TMPDIR: ${{ runner.temp }}

                  # tell Cypress more details about the context of this run
                  COMMIT_INFO_BRANCH: ${{ github.event.workflow_run.head_branch }}
                  COMMIT_INFO_SHA: ${{ github.event.workflow_run.head_sha }}
                  COMMIT_INFO_REMOTE: ${{ github.repositoryUrl }}
                  #COMMIT_INFO_MESSAGE: ${{ needs.prepare.outputs.commit_message }}
                  #COMMIT_INFO_AUTHOR: ${{ needs.prepare.outputs.commit_author }}
                  #COMMIT_INFO_EMAIL: ${{ needs.prepare.outputs.commit_email }}
                  #CYPRESS_PULL_REQUEST_ID: ${{ needs.prepare.outputs.pr_id }}
                  #CYPRESS_PULL_REQUEST_URL: https://github.com/${{ github.repository }}/pull/${{ needs.prepare.outputs.pr_id }}

            - name: Upload Artifact
              if: failure()
              uses: actions/upload-artifact@v3
              with:
                  name: cypress-results
                  path: |
                      matrix-react-sdk/cypress/screenshots
                      matrix-react-sdk/cypress/videos
                      matrix-react-sdk/cypress/synapselogs

            - name: Upload reports
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: cypress-junit
                  path: matrix-react-sdk/cypress/results

