name: Build downstream artifacts
on:
    pull_request: {}
    merge_group:
        types: [checks_requested]
    push:
        branches: [develop, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build-element-web:
        name: Build element-web
        # if: github.event_name == 'merge_group'
        uses: richvdh/matrix-react-sdk/.github/workflows/element-web.yaml@rav_work
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
